// Tipos e interfaces para Docentes
export interface Docente {
  id: number;
  codigo: string;
  nombres: string;
  apellidos: string;
  email: string;
  telefono: string;
  facultadId: number;
  programaId: number;
  especialidad: string;
  gradoAcademico: 'Bachiller' | 'Licenciado' | 'Magíster' | 'Doctor';
  cursosActivos: number;
  totalEstudiantes: number;
  añosExperiencia: number;
  horasSemanales: number;
  ultimaActividad: string;
  estado: 'activo' | 'inactivo' | 'licencia';
  tipoContrato: 'Nombrado' | 'Contratado' | 'Por Horas';
}

// Datos de docentes (simulados)
export const docentes: Docente[] = [
  // Facultad de Ciencias Empresariales - Administración de Empresas
  {
    id: 1,
    codigo: 'DOC-20180001',
    nombres: 'Carlos Alberto',
    apellidos: 'Mendoza Vásquez',
    email: 'carlos.mendoza@udh.edu.pe',
    telefono: '+51 962 345 678',
    facultadId: 1,
    programaId: 1,
    especialidad: 'Gestión Estratégica',
    gradoAcademico: 'Doctor',
    cursosActivos: 3,
    totalEstudiantes: 85,
    añosExperiencia: 12,
    horasSemanales: 20,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 2,
    codigo: 'DOC-20190015',
    nombres: 'María Fernanda',
    apellidos: 'Rojas Salazar',
    email: 'maria.rojas@udh.edu.pe',
    telefono: '+51 963 456 789',
    facultadId: 1,
    programaId: 1,
    especialidad: 'Recursos Humanos',
    gradoAcademico: 'Magíster',
    cursosActivos: 2,
    totalEstudiantes: 60,
    añosExperiencia: 8,
    horasSemanales: 16,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Contabilidad y Finanzas
  {
    id: 3,
    codigo: 'DOC-20170025',
    nombres: 'Jorge Luis',
    apellidos: 'Paredes Gutiérrez',
    email: 'jorge.paredes@udh.edu.pe',
    telefono: '+51 964 567 890',
    facultadId: 1,
    programaId: 2,
    especialidad: 'Contabilidad Financiera',
    gradoAcademico: 'Magíster',
    cursosActivos: 4,
    totalEstudiantes: 95,
    añosExperiencia: 15,
    horasSemanales: 24,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 4,
    codigo: 'DOC-20200032',
    nombres: 'Ana Patricia',
    apellidos: 'Torres Ramírez',
    email: 'ana.torres@udh.edu.pe',
    telefono: '+51 965 678 901',
    facultadId: 1,
    programaId: 2,
    especialidad: 'Auditoría',
    gradoAcademico: 'Licenciado',
    cursosActivos: 2,
    totalEstudiantes: 50,
    añosExperiencia: 5,
    horasSemanales: 12,
    ultimaActividad: '2025-10-27',
    estado: 'activo',
    tipoContrato: 'Por Horas'
  },
  
  // Marketing y Negocios Internacionales
  {
    id: 5,
    codigo: 'DOC-20180045',
    nombres: 'Roberto Carlos',
    apellidos: 'Díaz Huamán',
    email: 'roberto.diaz@udh.edu.pe',
    telefono: '+51 966 789 012',
    facultadId: 1,
    programaId: 3,
    especialidad: 'Marketing Digital',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 72,
    añosExperiencia: 10,
    horasSemanales: 18,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  {
    id: 6,
    codigo: 'DOC-20210050',
    nombres: 'Lucía Gabriela',
    apellidos: 'Campos Morales',
    email: 'lucia.campos@udh.edu.pe',
    telefono: '+51 967 890 123',
    facultadId: 1,
    programaId: 3,
    especialidad: 'Comercio Internacional',
    gradoAcademico: 'Doctor',
    cursosActivos: 2,
    totalEstudiantes: 55,
    añosExperiencia: 7,
    horasSemanales: 16,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  
  // Turismo, Hotelería y Gastronomía
  {
    id: 7,
    codigo: 'DOC-20190062',
    nombres: 'Fernando José',
    apellidos: 'Sánchez Pérez',
    email: 'fernando.sanchez@udh.edu.pe',
    telefono: '+51 968 901 234',
    facultadId: 1,
    programaId: 4,
    especialidad: 'Gestión Hotelera',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 68,
    añosExperiencia: 9,
    horasSemanales: 18,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Facultad de Derecho - Derecho y Ciencias Políticas
  {
    id: 8,
    codigo: 'DOC-20160075',
    nombres: 'Ricardo Antonio',
    apellidos: 'Vargas León',
    email: 'ricardo.vargas@udh.edu.pe',
    telefono: '+51 969 012 345',
    facultadId: 2,
    programaId: 5,
    especialidad: 'Derecho Constitucional',
    gradoAcademico: 'Doctor',
    cursosActivos: 4,
    totalEstudiantes: 110,
    añosExperiencia: 18,
    horasSemanales: 24,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 9,
    codigo: 'DOC-20180088',
    nombres: 'Patricia Elena',
    apellidos: 'Núñez Castro',
    email: 'patricia.nunez@udh.edu.pe',
    telefono: '+51 970 123 456',
    facultadId: 2,
    programaId: 5,
    especialidad: 'Derecho Penal',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 88,
    añosExperiencia: 11,
    horasSemanales: 20,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 10,
    codigo: 'DOC-20200095',
    nombres: 'Miguel Ángel',
    apellidos: 'Flores Quispe',
    email: 'miguel.flores@udh.edu.pe',
    telefono: '+51 971 234 567',
    facultadId: 2,
    programaId: 5,
    especialidad: 'Derecho Civil',
    gradoAcademico: 'Licenciado',
    cursosActivos: 2,
    totalEstudiantes: 52,
    añosExperiencia: 6,
    horasSemanales: 14,
    ultimaActividad: '2025-10-27',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Facultad de Ingeniería - Ingeniería de Sistemas
  {
    id: 11,
    codigo: 'DOC-20170105',
    nombres: 'Eduardo Martín',
    apellidos: 'Gonzales Herrera',
    email: 'eduardo.gonzales@udh.edu.pe',
    telefono: '+51 972 345 678',
    facultadId: 3,
    programaId: 6,
    especialidad: 'Desarrollo de Software',
    gradoAcademico: 'Doctor',
    cursosActivos: 4,
    totalEstudiantes: 105,
    añosExperiencia: 14,
    horasSemanales: 22,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 12,
    codigo: 'DOC-20190115',
    nombres: 'Diana Carolina',
    apellidos: 'Ramos Silva',
    email: 'diana.ramos@udh.edu.pe',
    telefono: '+51 973 456 789',
    facultadId: 3,
    programaId: 6,
    especialidad: 'Inteligencia Artificial',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 78,
    añosExperiencia: 8,
    horasSemanales: 18,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  {
    id: 13,
    codigo: 'DOC-20210125',
    nombres: 'Javier Alejandro',
    apellidos: 'Cruz Mendoza',
    email: 'javier.cruz@udh.edu.pe',
    telefono: '+51 974 567 890',
    facultadId: 3,
    programaId: 6,
    especialidad: 'Redes y Telecomunicaciones',
    gradoAcademico: 'Magíster',
    cursosActivos: 2,
    totalEstudiantes: 56,
    añosExperiencia: 5,
    horasSemanales: 16,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Por Horas'
  },
  
  // Ingeniería Civil
  {
    id: 14,
    codigo: 'DOC-20160135',
    nombres: 'Pedro Alejandro',
    apellidos: 'Quispe Tapia',
    email: 'pedro.quispe@udh.edu.pe',
    telefono: '+51 975 678 901',
    facultadId: 3,
    programaId: 7,
    especialidad: 'Estructuras',
    gradoAcademico: 'Doctor',
    cursosActivos: 3,
    totalEstudiantes: 82,
    añosExperiencia: 20,
    horasSemanales: 20,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 15,
    codigo: 'DOC-20180145',
    nombres: 'Rosa María',
    apellidos: 'Villanueva Ortiz',
    email: 'rosa.villanueva@udh.edu.pe',
    telefono: '+51 976 789 012',
    facultadId: 3,
    programaId: 7,
    especialidad: 'Geotecnia',
    gradoAcademico: 'Magíster',
    cursosActivos: 2,
    totalEstudiantes: 58,
    añosExperiencia: 10,
    horasSemanales: 16,
    ultimaActividad: '2025-10-27',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Ingeniería Ambiental
  {
    id: 16,
    codigo: 'DOC-20190155',
    nombres: 'Luis Fernando',
    apellidos: 'Chávez Rojas',
    email: 'luis.chavez@udh.edu.pe',
    telefono: '+51 977 890 123',
    facultadId: 3,
    programaId: 8,
    especialidad: 'Gestión Ambiental',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 65,
    añosExperiencia: 9,
    horasSemanales: 18,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 17,
    codigo: 'DOC-20200165',
    nombres: 'Carmen Sofía',
    apellidos: 'Acosta Prado',
    email: 'carmen.acosta@udh.edu.pe',
    telefono: '+51 978 901 234',
    facultadId: 3,
    programaId: 8,
    especialidad: 'Recursos Hídricos',
    gradoAcademico: 'Doctor',
    cursosActivos: 2,
    totalEstudiantes: 48,
    añosExperiencia: 7,
    horasSemanales: 16,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Arquitectura
  {
    id: 18,
    codigo: 'DOC-20170175',
    nombres: 'Alberto José',
    apellidos: 'Medina Cárdenas',
    email: 'alberto.medina@udh.edu.pe',
    telefono: '+51 979 012 345',
    facultadId: 3,
    programaId: 9,
    especialidad: 'Diseño Arquitectónico',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 70,
    añosExperiencia: 12,
    horasSemanales: 20,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  
  // Facultad de Ciencias de la Salud - Enfermería
  {
    id: 19,
    codigo: 'DOC-20160185',
    nombres: 'Mónica Isabel',
    apellidos: 'García Rivas',
    email: 'monica.garcia@udh.edu.pe',
    telefono: '+51 980 123 456',
    facultadId: 4,
    programaId: 10,
    especialidad: 'Enfermería Clínica',
    gradoAcademico: 'Magíster',
    cursosActivos: 4,
    totalEstudiantes: 92,
    añosExperiencia: 16,
    horasSemanales: 22,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 20,
    codigo: 'DOC-20190195',
    nombres: 'Sandra Beatriz',
    apellidos: 'López Fernández',
    email: 'sandra.lopez@udh.edu.pe',
    telefono: '+51 981 234 567',
    facultadId: 4,
    programaId: 10,
    especialidad: 'Cuidados Intensivos',
    gradoAcademico: 'Licenciado',
    cursosActivos: 2,
    totalEstudiantes: 54,
    añosExperiencia: 8,
    horasSemanales: 16,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Obstetricia
  {
    id: 21,
    codigo: 'DOC-20180205',
    nombres: 'Gloria Elena',
    apellidos: 'Martínez Díaz',
    email: 'gloria.martinez@udh.edu.pe',
    telefono: '+51 982 345 678',
    facultadId: 4,
    programaId: 11,
    especialidad: 'Salud Reproductiva',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 68,
    añosExperiencia: 13,
    horasSemanales: 18,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  
  // Odontología
  {
    id: 22,
    codigo: 'DOC-20170215',
    nombres: 'Héctor Manuel',
    apellidos: 'Castillo Vega',
    email: 'hector.castillo@udh.edu.pe',
    telefono: '+51 983 456 789',
    facultadId: 4,
    programaId: 12,
    especialidad: 'Ortodoncia',
    gradoAcademico: 'Doctor',
    cursosActivos: 3,
    totalEstudiantes: 62,
    añosExperiencia: 15,
    horasSemanales: 20,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 23,
    codigo: 'DOC-20200225',
    nombres: 'Valeria Cristina',
    apellidos: 'Pinto Herrera',
    email: 'valeria.pinto@udh.edu.pe',
    telefono: '+51 984 567 890',
    facultadId: 4,
    programaId: 12,
    especialidad: 'Periodoncia',
    gradoAcademico: 'Magíster',
    cursosActivos: 2,
    totalEstudiantes: 45,
    añosExperiencia: 6,
    horasSemanales: 14,
    ultimaActividad: '2025-10-27',
    estado: 'activo',
    tipoContrato: 'Por Horas'
  },
  
  // Psicología
  {
    id: 24,
    codigo: 'DOC-20180235',
    nombres: 'Andrés Felipe',
    apellidos: 'Reyes Morales',
    email: 'andres.reyes@udh.edu.pe',
    telefono: '+51 985 678 901',
    facultadId: 4,
    programaId: 13,
    especialidad: 'Psicología Clínica',
    gradoAcademico: 'Doctor',
    cursosActivos: 4,
    totalEstudiantes: 98,
    añosExperiencia: 12,
    horasSemanales: 22,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 25,
    codigo: 'DOC-20190245',
    nombres: 'Daniela Alejandra',
    apellidos: 'Suárez Ríos',
    email: 'daniela.suarez@udh.edu.pe',
    telefono: '+51 986 789 012',
    facultadId: 4,
    programaId: 13,
    especialidad: 'Psicología Organizacional',
    gradoAcademico: 'Magíster',
    cursosActivos: 3,
    totalEstudiantes: 74,
    añosExperiencia: 9,
    horasSemanales: 18,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Facultad de Educación - Educación Básica
  {
    id: 26,
    codigo: 'DOC-20160255',
    nombres: 'Teresa Margarita',
    apellidos: 'Hidalgo Cáceres',
    email: 'teresa.hidalgo@udh.edu.pe',
    telefono: '+51 987 890 123',
    facultadId: 5,
    programaId: 14,
    especialidad: 'Educación Inicial',
    gradoAcademico: 'Magíster',
    cursosActivos: 4,
    totalEstudiantes: 86,
    añosExperiencia: 18,
    horasSemanales: 22,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 27,
    codigo: 'DOC-20180265',
    nombres: 'Raúl Ernesto',
    apellidos: 'Cordero Paz',
    email: 'raul.cordero@udh.edu.pe',
    telefono: '+51 988 901 234',
    facultadId: 5,
    programaId: 14,
    especialidad: 'Educación Primaria',
    gradoAcademico: 'Doctor',
    cursosActivos: 3,
    totalEstudiantes: 72,
    añosExperiencia: 14,
    horasSemanales: 20,
    ultimaActividad: '2025-10-28',
    estado: 'activo',
    tipoContrato: 'Nombrado'
  },
  {
    id: 28,
    codigo: 'DOC-20200275',
    nombres: 'Silvia Roxana',
    apellidos: 'Navarro Espinoza',
    email: 'silvia.navarro@udh.edu.pe',
    telefono: '+51 989 012 345',
    facultadId: 5,
    programaId: 14,
    especialidad: 'Didáctica',
    gradoAcademico: 'Magíster',
    cursosActivos: 2,
    totalEstudiantes: 58,
    añosExperiencia: 7,
    horasSemanales: 16,
    ultimaActividad: '2025-10-29',
    estado: 'activo',
    tipoContrato: 'Contratado'
  },
  
  // Algunos docentes con otros estados
  {
    id: 29,
    codigo: 'DOC-20150285',
    nombres: 'Guillermo Arturo',
    apellidos: 'Benavides Lagos',
    email: 'guillermo.benavides@udh.edu.pe',
    telefono: '+51 990 123 456',
    facultadId: 1,
    programaId: 1,
    especialidad: 'Finanzas Corporativas',
    gradoAcademico: 'Doctor',
    cursosActivos: 0,
    totalEstudiantes: 0,
    añosExperiencia: 22,
    horasSemanales: 0,
    ultimaActividad: '2025-08-15',
    estado: 'licencia',
    tipoContrato: 'Nombrado'
  },
  {
    id: 30,
    codigo: 'DOC-20190295',
    nombres: 'Verónica Isabel',
    apellidos: 'Palomino Cruz',
    email: 'veronica.palomino@udh.edu.pe',
    telefono: '+51 991 234 567',
    facultadId: 3,
    programaId: 6,
    especialidad: 'Base de Datos',
    gradoAcademico: 'Licenciado',
    cursosActivos: 0,
    totalEstudiantes: 0,
    añosExperiencia: 4,
    horasSemanales: 0,
    ultimaActividad: '2025-06-30',
    estado: 'inactivo',
    tipoContrato: 'Por Horas'
  }
];
