// Tipos e interfaces
export interface Estudiante {
  id: number;
  codigo: string;
  nombres: string;
  apellidos: string;
  email: string;
  telefono: string;
  facultadId: number;
  programaId: number;
  ciclo: string;
  promedio: number;
  asistencia: number;
  tareasEntregadas: number;
  tareasTotal: number;
  ultimaActividad: string;
  estado: 'activo' | 'inactivo' | 'suspendido';
}

export interface Facultad {
  id: number;
  nombre: string;
  icon: string;
  color: string;
}

export interface ProgramaAcademico {
  id: number;
  facultadId: number;
  nombre: string;
  codigo: string;
  ciclosTotal: number;
  color?: string;
  ciclosDisponibles?: string[];
}

// Datos de facultades
export const facultades: Facultad[] = [
  {
    id: 1,
    nombre: 'Ciencias Empresariales',
    icon: '🏛',
    color: '#3b82f6'
  },
  {
    id: 2,
    nombre: 'Derecho y Ciencias Políticas',
    icon: '⚖️',
    color: '#f59e0b'
  },
  {
    id: 3,
    nombre: 'Ingeniería',
    icon: '🖥',
    color: '#8b5cf6'
  },
  {
    id: 4,
    nombre: 'Ciencias de la Salud',
    icon: '🧠',
    color: '#ec4899'
  },
  {
    id: 5,
    nombre: 'Educación',
    icon: '📚',
    color: '#10b981'
  }
];

// Datos de programas académicos
export const programas: ProgramaAcademico[] = [
  // Ciencias Empresariales
  {
    id: 1,
    facultadId: 1,
    nombre: 'Administración de Empresas',
    codigo: 'ADM',
    ciclosTotal: 10
  },
  {
    id: 2,
    facultadId: 1,
    nombre: 'Contabilidad y Finanzas',
    codigo: 'CONT',
    ciclosTotal: 10
  },
  {
    id: 3,
    facultadId: 1,
    nombre: 'Marketing y Negocios Internacionales',
    codigo: 'MKT',
    ciclosTotal: 10
  },
  {
    id: 4,
    facultadId: 1,
    nombre: 'Turismo, Hotelería y Gastronomía',
    codigo: 'TUR',
    ciclosTotal: 10
  },
  // Derecho y Ciencias Políticas
  {
    id: 5,
    facultadId: 2,
    nombre: 'Derecho y Ciencias Políticas',
    codigo: 'DER',
    ciclosTotal: 10
  },
  // Ingeniería
  {
    id: 6,
    facultadId: 3,
    nombre: 'Ingeniería de Sistemas e Informática',
    codigo: 'ISI',
    ciclosTotal: 10
  },
  {
    id: 7,
    facultadId: 3,
    nombre: 'Ingeniería Civil',
    codigo: 'IC',
    ciclosTotal: 10
  },
  {
    id: 8,
    facultadId: 3,
    nombre: 'Ingeniería Ambiental',
    codigo: 'IA',
    ciclosTotal: 10
  },
  {
    id: 9,
    facultadId: 3,
    nombre: 'Arquitectura',
    codigo: 'ARQ',
    ciclosTotal: 10
  },
  // Ciencias de la Salud
  {
    id: 10,
    facultadId: 4,
    nombre: 'Enfermería',
    codigo: 'ENF',
    ciclosTotal: 10
  },
  {
    id: 11,
    facultadId: 4,
    nombre: 'Obstetricia',
    codigo: 'OBS',
    ciclosTotal: 10
  },
  {
    id: 12,
    facultadId: 4,
    nombre: 'Odontología',
    codigo: 'ODO',
    ciclosTotal: 10
  },
  {
    id: 13,
    facultadId: 4,
    nombre: 'Psicología',
    codigo: 'PSI',
    ciclosTotal: 10
  },
  // Educación
  {
    id: 14,
    facultadId: 5,
    nombre: 'Educación Básica: Inicial y Primaria',
    codigo: 'EDU',
    ciclosTotal: 10
  }
];

// Datos de estudiantes
export const estudiantes: Estudiante[] = [
  // ============= CIENCIAS EMPRESARIALES - ADMINISTRACIÓN =============
  {
    id: 1,
    codigo: '2021001',
    nombres: 'Ana María',
    apellidos: 'García López',
    email: 'ana.garcia@udh.edu.pe',
    telefono: '+51 987 654 321',
    facultadId: 1,
    programaId: 1,
    ciclo: 'VIII',
    promedio: 16.8,
    asistencia: 95,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 2,
    codigo: '2022015',
    nombres: 'Roberto',
    apellidos: 'Pérez Sandoval',
    email: 'roberto.perez@udh.edu.pe',
    telefono: '+51 987 654 401',
    facultadId: 1,
    programaId: 1,
    ciclo: 'II',
    promedio: 15.5,
    asistencia: 92,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 3,
    codigo: '2020016',
    nombres: 'Patricia',
    apellidos: 'Luna Ramírez',
    email: 'patricia.luna@udh.edu.pe',
    telefono: '+51 987 654 402',
    facultadId: 1,
    programaId: 1,
    ciclo: 'X',
    promedio: 17.2,
    asistencia: 98,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 30 min',
    estado: 'activo'
  },
  {
    id: 4,
    codigo: '2021017',
    nombres: 'Javier',
    apellidos: 'Flores Medina',
    email: 'javier.flores@udh.edu.pe',
    telefono: '+51 987 654 403',
    facultadId: 1,
    programaId: 1,
    ciclo: 'V',
    promedio: 14.9,
    asistencia: 85,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 días',
    estado: 'activo'
  },

  // ============= CIENCIAS EMPRESARIALES - CONTABILIDAD =============
  {
    id: 5,
    codigo: '2021002',
    nombres: 'Carlos Eduardo',
    apellidos: 'López Martínez',
    email: 'carlos.lopez@udh.edu.pe',
    telefono: '+51 987 654 322',
    facultadId: 1,
    programaId: 2,
    ciclo: 'VI',
    promedio: 15.2,
    asistencia: 88,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },
  {
    id: 6,
    codigo: '2022018',
    nombres: 'Andrea',
    apellidos: 'Castillo Vega',
    email: 'andrea.castillo@udh.edu.pe',
    telefono: '+51 987 654 404',
    facultadId: 1,
    programaId: 2,
    ciclo: 'III',
    promedio: 16.7,
    asistencia: 94,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 7,
    codigo: '2021019',
    nombres: 'Miguel Ángel',
    apellidos: 'Torres Quispe',
    email: 'miguel.torres@udh.edu.pe',
    telefono: '+51 987 654 405',
    facultadId: 1,
    programaId: 2,
    ciclo: 'VII',
    promedio: 17.1,
    asistencia: 96,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 horas',
    estado: 'activo'
  },
  {
    id: 8,
    codigo: '2020020',
    nombres: 'Rosa',
    apellidos: 'Huamán Silva',
    email: 'rosa.huaman@udh.edu.pe',
    telefono: '+51 987 654 406',
    facultadId: 1,
    programaId: 2,
    ciclo: 'IX',
    promedio: 15.8,
    asistencia: 90,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },

  // ============= CIENCIAS EMPRESARIALES - MARKETING =============
  {
    id: 9,
    codigo: '2021003',
    nombres: 'María José',
    apellidos: 'Fernández Silva',
    email: 'maria.fernandez@udh.edu.pe',
    telefono: '+51 987 654 323',
    facultadId: 1,
    programaId: 3,
    ciclo: 'IV',
    promedio: 17.5,
    asistencia: 98,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 30 min',
    estado: 'activo'
  },
  {
    id: 10,
    codigo: '2022021',
    nombres: 'Franco',
    apellidos: 'Sánchez Rojas',
    email: 'franco.sanchez@udh.edu.pe',
    telefono: '+51 987 654 407',
    facultadId: 1,
    programaId: 3,
    ciclo: 'I',
    promedio: 14.5,
    asistencia: 87,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 5 horas',
    estado: 'activo'
  },
  {
    id: 11,
    codigo: '2021022',
    nombres: 'Diana',
    apellidos: 'Mendoza Arce',
    email: 'diana.mendoza@udh.edu.pe',
    telefono: '+51 987 654 408',
    facultadId: 1,
    programaId: 3,
    ciclo: 'VI',
    promedio: 16.3,
    asistencia: 93,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 12,
    codigo: '2020023',
    nombres: 'Luis Alberto',
    apellidos: 'Cárdenas Pinto',
    email: 'luis.cardenas@udh.edu.pe',
    telefono: '+51 987 654 409',
    facultadId: 1,
    programaId: 3,
    ciclo: 'VIII',
    promedio: 15.9,
    asistencia: 89,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },

  // ============= CIENCIAS EMPRESARIALES - TURISMO =============
  {
    id: 13,
    codigo: '2020004',
    nombres: 'Jorge Luis',
    apellidos: 'Martínez Rojas',
    email: 'jorge.martinez@udh.edu.pe',
    telefono: '+51 987 654 324',
    facultadId: 1,
    programaId: 4,
    ciclo: 'X',
    promedio: 14.8,
    asistencia: 75,
    tareasEntregadas: 6,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 días',
    estado: 'inactivo'
  },
  {
    id: 14,
    codigo: '2022024',
    nombres: 'Valeria',
    apellidos: 'Paredes Lozano',
    email: 'valeria.paredes@udh.edu.pe',
    telefono: '+51 987 654 410',
    facultadId: 1,
    programaId: 4,
    ciclo: 'II',
    promedio: 16.8,
    asistencia: 95,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 15,
    codigo: '2021025',
    nombres: 'Fernando',
    apellidos: 'Ríos Campos',
    email: 'fernando.rios@udh.edu.pe',
    telefono: '+51 987 654 411',
    facultadId: 1,
    programaId: 4,
    ciclo: 'V',
    promedio: 15.4,
    asistencia: 91,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 6 horas',
    estado: 'activo'
  },

  // ============= DERECHO Y CIENCIAS POLÍTICAS =============
  {
    id: 16,
    codigo: '2021005',
    nombres: 'Lucía',
    apellidos: 'Ramírez Torres',
    email: 'lucia.ramirez@udh.edu.pe',
    telefono: '+51 987 654 325',
    facultadId: 2,
    programaId: 5,
    ciclo: 'VII',
    promedio: 18.2,
    asistencia: 100,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 17,
    codigo: '2022026',
    nombres: 'Andrés',
    apellidos: 'Gutiérrez Salazar',
    email: 'andres.gutierrez@udh.edu.pe',
    telefono: '+51 987 654 412',
    facultadId: 2,
    programaId: 5,
    ciclo: 'II',
    promedio: 15.6,
    asistencia: 88,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 horas',
    estado: 'activo'
  },
  {
    id: 18,
    codigo: '2021027',
    nombres: 'Carmen',
    apellidos: 'Vásquez León',
    email: 'carmen.vasquez@udh.edu.pe',
    telefono: '+51 987 654 413',
    facultadId: 2,
    programaId: 5,
    ciclo: 'VI',
    promedio: 17.4,
    asistencia: 97,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 19,
    codigo: '2020028',
    nombres: 'Ricardo',
    apellidos: 'Espinoza Díaz',
    email: 'ricardo.espinoza@udh.edu.pe',
    telefono: '+51 987 654 414',
    facultadId: 2,
    programaId: 5,
    ciclo: 'IX',
    promedio: 16.1,
    asistencia: 92,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },
  {
    id: 20,
    codigo: '2021029',
    nombres: 'Gabriela',
    apellidos: 'Moreno Palacios',
    email: 'gabriela.moreno@udh.edu.pe',
    telefono: '+51 987 654 415',
    facultadId: 2,
    programaId: 5,
    ciclo: 'IV',
    promedio: 16.9,
    asistencia: 94,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 horas',
    estado: 'activo'
  },

  // ============= INGENIERÍA - SISTEMAS E INFORMÁTICA =============
  {
    id: 21,
    codigo: '2021006',
    nombres: 'Pedro Antonio',
    apellidos: 'González Díaz',
    email: 'pedro.gonzalez@udh.edu.pe',
    telefono: '+51 987 654 326',
    facultadId: 3,
    programaId: 6,
    ciclo: 'V',
    promedio: 16.0,
    asistencia: 92,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 5 horas',
    estado: 'activo'
  },
  {
    id: 22,
    codigo: '2022030',
    nombres: 'Jessica',
    apellidos: 'Rojas Vargas',
    email: 'jessica.rojas@udh.edu.pe',
    telefono: '+51 987 654 416',
    facultadId: 3,
    programaId: 6,
    ciclo: 'I',
    promedio: 17.3,
    asistencia: 96,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 23,
    codigo: '2021031',
    nombres: 'Eduardo',
    apellidos: 'Silva Montes',
    email: 'eduardo.silva@udh.edu.pe',
    telefono: '+51 987 654 417',
    facultadId: 3,
    programaId: 6,
    ciclo: 'VII',
    promedio: 15.7,
    asistencia: 89,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },
  {
    id: 24,
    codigo: '2020032',
    nombres: 'Natalia',
    apellidos: 'Cruz Herrera',
    email: 'natalia.cruz@udh.edu.pe',
    telefono: '+51 987 654 418',
    facultadId: 3,
    programaId: 6,
    ciclo: 'X',
    promedio: 18.1,
    asistencia: 99,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 30 min',
    estado: 'activo'
  },
  {
    id: 25,
    codigo: '2022033',
    nombres: 'Raúl',
    apellidos: 'Carrillo Paz',
    email: 'raul.carrillo@udh.edu.pe',
    telefono: '+51 987 654 419',
    facultadId: 3,
    programaId: 6,
    ciclo: 'III',
    promedio: 14.8,
    asistencia: 86,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 días',
    estado: 'activo'
  },

  // ============= INGENIERÍA - CIVIL =============
  {
    id: 26,
    codigo: '2021007',
    nombres: 'Sofía Isabel',
    apellidos: 'Mendoza Cruz',
    email: 'sofia.mendoza@udh.edu.pe',
    telefono: '+51 987 654 327',
    facultadId: 3,
    programaId: 7,
    ciclo: 'III',
    promedio: 15.8,
    asistencia: 90,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 días',
    estado: 'activo'
  },
  {
    id: 27,
    codigo: '2022034',
    nombres: 'Daniel',
    apellidos: 'Alvarado Ríos',
    email: 'daniel.alvarado@udh.edu.pe',
    telefono: '+51 987 654 420',
    facultadId: 3,
    programaId: 7,
    ciclo: 'I',
    promedio: 16.4,
    asistencia: 93,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 horas',
    estado: 'activo'
  },
  {
    id: 28,
    codigo: '2021035',
    nombres: 'Elena',
    apellidos: 'Soto Figueroa',
    email: 'elena.soto@udh.edu.pe',
    telefono: '+51 987 654 421',
    facultadId: 3,
    programaId: 7,
    ciclo: 'VI',
    promedio: 17.0,
    asistencia: 95,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 29,
    codigo: '2020036',
    nombres: 'Manuel',
    apellidos: 'Delgado Núñez',
    email: 'manuel.delgado@udh.edu.pe',
    telefono: '+51 987 654 422',
    facultadId: 3,
    programaId: 7,
    ciclo: 'VIII',
    promedio: 15.2,
    asistencia: 87,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 días',
    estado: 'activo'
  },

  // ============= INGENIERÍA - AMBIENTAL =============
  {
    id: 30,
    codigo: '2021008',
    nombres: 'Diego Alejandro',
    apellidos: 'Vargas Pérez',
    email: 'diego.vargas@udh.edu.pe',
    telefono: '+51 987 654 328',
    facultadId: 3,
    programaId: 8,
    ciclo: 'IX',
    promedio: 13.5,
    asistencia: 70,
    tareasEntregadas: 5,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 semana',
    estado: 'suspendido'
  },
  {
    id: 31,
    codigo: '2022037',
    nombres: 'Laura',
    apellidos: 'Morales Chávez',
    email: 'laura.morales@udh.edu.pe',
    telefono: '+51 987 654 423',
    facultadId: 3,
    programaId: 8,
    ciclo: 'II',
    promedio: 17.6,
    asistencia: 98,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 32,
    codigo: '2021038',
    nombres: 'Óscar',
    apellidos: 'Jiménez Sánchez',
    email: 'oscar.jimenez@udh.edu.pe',
    telefono: '+51 987 654 424',
    facultadId: 3,
    programaId: 8,
    ciclo: 'V',
    promedio: 16.2,
    asistencia: 91,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 5 horas',
    estado: 'activo'
  },
  {
    id: 33,
    codigo: '2020039',
    nombres: 'Paola',
    apellidos: 'Reyes Villanueva',
    email: 'paola.reyes@udh.edu.pe',
    telefono: '+51 987 654 425',
    facultadId: 3,
    programaId: 8,
    ciclo: 'VII',
    promedio: 15.9,
    asistencia: 89,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 días',
    estado: 'activo'
  },

  // ============= INGENIERÍA - ARQUITECTURA =============
  {
    id: 34,
    codigo: '2022009',
    nombres: 'Valentina',
    apellidos: 'Ruiz Castro',
    email: 'valentina.ruiz@udh.edu.pe',
    telefono: '+51 987 654 329',
    facultadId: 3,
    programaId: 9,
    ciclo: 'II',
    promedio: 17.0,
    asistencia: 96,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 horas',
    estado: 'activo'
  },
  {
    id: 35,
    codigo: '2021040',
    nombres: 'Cristian',
    apellidos: 'Navarro Ortega',
    email: 'cristian.navarro@udh.edu.pe',
    telefono: '+51 987 654 426',
    facultadId: 3,
    programaId: 9,
    ciclo: 'IV',
    promedio: 16.5,
    asistencia: 92,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 36,
    codigo: '2021041',
    nombres: 'Alejandra',
    apellidos: 'Guerrero Ramos',
    email: 'alejandra.guerrero@udh.edu.pe',
    telefono: '+51 987 654 427',
    facultadId: 3,
    programaId: 9,
    ciclo: 'VI',
    promedio: 18.3,
    asistencia: 100,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 30 min',
    estado: 'activo'
  },
  {
    id: 37,
    codigo: '2020042',
    nombres: 'Sergio',
    apellidos: 'Campos Alarcón',
    email: 'sergio.campos@udh.edu.pe',
    telefono: '+51 987 654 428',
    facultadId: 3,
    programaId: 9,
    ciclo: 'IX',
    promedio: 15.4,
    asistencia: 88,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 días',
    estado: 'activo'
  },

  // ============= CIENCIAS DE LA SALUD - ENFERMERÍA =============
  {
    id: 38,
    codigo: '2022010',
    nombres: 'Gabriel',
    apellidos: 'Morales Herrera',
    email: 'gabriel.morales@udh.edu.pe',
    telefono: '+51 987 654 330',
    facultadId: 4,
    programaId: 10,
    ciclo: 'IV',
    promedio: 16.5,
    asistencia: 93,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 horas',
    estado: 'activo'
  },
  {
    id: 39,
    codigo: '2022043',
    nombres: 'Daniela',
    apellidos: 'Ibarra Pérez',
    email: 'daniela.ibarra@udh.edu.pe',
    telefono: '+51 987 654 429',
    facultadId: 4,
    programaId: 10,
    ciclo: 'I',
    promedio: 17.8,
    asistencia: 97,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 40,
    codigo: '2021044',
    nombres: 'Esteban',
    apellidos: 'Valdez Miranda',
    email: 'esteban.valdez@udh.edu.pe',
    telefono: '+51 987 654 430',
    facultadId: 4,
    programaId: 10,
    ciclo: 'VI',
    promedio: 16.1,
    asistencia: 90,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 6 horas',
    estado: 'activo'
  },
  {
    id: 41,
    codigo: '2020045',
    nombres: 'Mónica',
    apellidos: 'Herrera Salinas',
    email: 'monica.herrera@udh.edu.pe',
    telefono: '+51 987 654 431',
    facultadId: 4,
    programaId: 10,
    ciclo: 'VIII',
    promedio: 15.7,
    asistencia: 89,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },

  // ============= CIENCIAS DE LA SALUD - OBSTETRICIA =============
  {
    id: 42,
    codigo: '2021011',
    nombres: 'Isabella',
    apellidos: 'Santos Vega',
    email: 'isabella.santos@udh.edu.pe',
    telefono: '+51 987 654 331',
    facultadId: 4,
    programaId: 11,
    ciclo: 'VI',
    promedio: 17.8,
    asistencia: 99,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 43,
    codigo: '2022046',
    nombres: 'Mariana',
    apellidos: 'Pacheco Ruiz',
    email: 'mariana.pacheco@udh.edu.pe',
    telefono: '+51 987 654 432',
    facultadId: 4,
    programaId: 11,
    ciclo: 'II',
    promedio: 16.4,
    asistencia: 92,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 horas',
    estado: 'activo'
  },
  {
    id: 44,
    codigo: '2021047',
    nombres: 'Beatriz',
    apellidos: 'Aguilar Coronel',
    email: 'beatriz.aguilar@udh.edu.pe',
    telefono: '+51 987 654 433',
    facultadId: 4,
    programaId: 11,
    ciclo: 'IV',
    promedio: 17.2,
    asistencia: 95,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 45,
    codigo: '2020048',
    nombres: 'Cecilia',
    apellidos: 'Trujillo Medina',
    email: 'cecilia.trujillo@udh.edu.pe',
    telefono: '+51 987 654 434',
    facultadId: 4,
    programaId: 11,
    ciclo: 'IX',
    promedio: 16.9,
    asistencia: 94,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 5 horas',
    estado: 'activo'
  },

  // ============= CIENCIAS DE LA SALUD - ODONTOLOGÍA =============
  {
    id: 46,
    codigo: '2021012',
    nombres: 'Sebastián',
    apellidos: 'Campos Navarro',
    email: 'sebastian.campos@udh.edu.pe',
    telefono: '+51 987 654 332',
    facultadId: 4,
    programaId: 12,
    ciclo: 'VIII',
    promedio: 15.5,
    asistencia: 87,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 6 horas',
    estado: 'activo'
  },
  {
    id: 47,
    codigo: '2022049',
    nombres: 'Fernanda',
    apellidos: 'Becerra Gómez',
    email: 'fernanda.becerra@udh.edu.pe',
    telefono: '+51 987 654 435',
    facultadId: 4,
    programaId: 12,
    ciclo: 'I',
    promedio: 17.5,
    asistencia: 96,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 48,
    codigo: '2021050',
    nombres: 'Julio',
    apellidos: 'Montoya Suárez',
    email: 'julio.montoya@udh.edu.pe',
    telefono: '+51 987 654 436',
    facultadId: 4,
    programaId: 12,
    ciclo: 'V',
    promedio: 16.3,
    asistencia: 91,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 día',
    estado: 'activo'
  },
  {
    id: 49,
    codigo: '2020051',
    nombres: 'Victoria',
    apellidos: 'Zárate Calderón',
    email: 'victoria.zarate@udh.edu.pe',
    telefono: '+51 987 654 437',
    facultadId: 4,
    programaId: 12,
    ciclo: 'X',
    promedio: 18.0,
    asistencia: 98,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 horas',
    estado: 'activo'
  },

  // ============= CIENCIAS DE LA SALUD - PSICOLOGÍA =============
  {
    id: 50,
    codigo: '2022013',
    nombres: 'Camila',
    apellidos: 'Ortiz Paredes',
    email: 'camila.ortiz@udh.edu.pe',
    telefono: '+51 987 654 333',
    facultadId: 4,
    programaId: 13,
    ciclo: 'III',
    promedio: 18.0,
    asistencia: 100,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 45 min',
    estado: 'activo'
  },
  {
    id: 51,
    codigo: '2022052',
    nombres: 'Adrián',
    apellidos: 'Peña Cortez',
    email: 'adrian.pena@udh.edu.pe',
    telefono: '+51 987 654 438',
    facultadId: 4,
    programaId: 13,
    ciclo: 'I',
    promedio: 15.8,
    asistencia: 88,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 7 horas',
    estado: 'activo'
  },
  {
    id: 52,
    codigo: '2021053',
    nombres: 'Luciana',
    apellidos: 'Bravo Fuentes',
    email: 'luciana.bravo@udh.edu.pe',
    telefono: '+51 987 654 439',
    facultadId: 4,
    programaId: 13,
    ciclo: 'V',
    promedio: 17.1,
    asistencia: 95,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 53,
    codigo: '2021054',
    nombres: 'Emilio',
    apellidos: 'Castro Villena',
    email: 'emilio.castro@udh.edu.pe',
    telefono: '+51 987 654 440',
    facultadId: 4,
    programaId: 13,
    ciclo: 'VII',
    promedio: 16.6,
    asistencia: 93,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 4 horas',
    estado: 'activo'
  },

  // ============= EDUCACIÓN - INICIAL Y PRIMARIA =============
  {
    id: 54,
    codigo: '2021014',
    nombres: 'Mateo',
    apellidos: 'Reyes Soto',
    email: 'mateo.reyes@udh.edu.pe',
    telefono: '+51 987 654 334',
    facultadId: 5,
    programaId: 14,
    ciclo: 'V',
    promedio: 16.2,
    asistencia: 91,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 horas',
    estado: 'activo'
  },
  {
    id: 55,
    codigo: '2022055',
    nombres: 'Sofía',
    apellidos: 'Romero Aguirre',
    email: 'sofia.romero@udh.edu.pe',
    telefono: '+51 987 654 441',
    facultadId: 5,
    programaId: 14,
    ciclo: 'II',
    promedio: 17.7,
    asistencia: 97,
    tareasEntregadas: 10,
    tareasTotal: 10,
    ultimaActividad: 'Hace 1 hora',
    estado: 'activo'
  },
  {
    id: 56,
    codigo: '2021056',
    nombres: 'Nicolás',
    apellidos: 'Prado Márquez',
    email: 'nicolas.prado@udh.edu.pe',
    telefono: '+51 987 654 442',
    facultadId: 5,
    programaId: 14,
    ciclo: 'VI',
    promedio: 15.9,
    asistencia: 89,
    tareasEntregadas: 8,
    tareasTotal: 10,
    ultimaActividad: 'Hace 5 horas',
    estado: 'activo'
  },
  {
    id: 57,
    codigo: '2020057',
    nombres: 'Ximena',
    apellidos: 'León Bustamante',
    email: 'ximena.leon@udh.edu.pe',
    telefono: '+51 987 654 443',
    facultadId: 5,
    programaId: 14,
    ciclo: 'VIII',
    promedio: 16.8,
    asistencia: 94,
    tareasEntregadas: 9,
    tareasTotal: 10,
    ultimaActividad: 'Hace 3 horas',
    estado: 'activo'
  },
  {
    id: 58,
    codigo: '2021058',
    nombres: 'Matías',
    apellidos: 'Figueroa Santos',
    email: 'matias.figueroa@udh.edu.pe',
    telefono: '+51 987 654 444',
    facultadId: 5,
    programaId: 14,
    ciclo: 'IV',
    promedio: 14.5,
    asistencia: 82,
    tareasEntregadas: 7,
    tareasTotal: 10,
    ultimaActividad: 'Hace 2 días',
    estado: 'activo'
  }
];
